Iter13
mbiwapa/metric pull request #13
Opened 2024-01-21 10:06 UTC by mbiwapa

2024-01-22 16:36 UTC, rktkov requested changes

2024-01-22 16:36 UTC, rktkov commented on internal/storage/postgre/postgre.go
> +func Backoff() backoff.Algorithm {
Обязательно должен быть открытый метод?

2024-01-22 16:36 UTC, rktkov commented on internal/storage/postgre/postgre.go
> +	err := retry.Retry(
Я не уверен, что тут логика retry нужна, по крайне мере на уровне хранилища. Пусть клиентский код решает, хочет ли он повторять попытку или нет.

2024-01-22 16:36 UTC, rktkov commented on internal/storage/postgre/postgre.go
> +	err := retry.Retry(
См. комментарий выше.

2024-01-22 16:36 UTC, rktkov commented on internal/storage/postgre/postgre.go
> +	err := retry.Retry(
см. комментарий к другим update методам.

2024-01-22 16:36 UTC, rktkov commented on internal/storage/postgre/postgre.go
> +		stmt, err := tx.PrepareContext(ctx, `INSERT INTO metric (name, gauge, counter) VALUES ($1,$2,$3) ON CONFLICT (name) DO UPDATE SET gauge=$2, counter=$3`)
Я бы попробовал изменить запрос таким образом, чтобы можно было за один раз добавить несколько значений. А не генерировал бы много запросов.

2024-01-22 16:36 UTC, rktkov commented on internal/agent/client/client.go
> +		strategy.Backoff(func(attempt uint) time.Duration {
Вижу повторяющейся код.

2024-01-22 16:36 UTC, rktkov commented on internal/server/handlers/ping/ping.go
> +	"go.uber.org/zap"
Настал момент спрятать zap во внутренний пакет логгера и убрать зависимость от реализации логгера.

2024-01-26 09:44 UTC, mbiwapa commented on internal/storage/postgre/postgre.go
> +		stmt, err := tx.PrepareContext(ctx, `INSERT INTO metric (name, gauge, counter) VALUES ($1,$2,$3) ON CONFLICT (name) DO UPDATE SET gauge=$2, counter=$3`)
Ты имешь ввиду вот так?
`INSERT INTO metric (name, gauge, counter) VALUES 
('name1', 2.3, 5), 
('name2', 2.5, 28), 
('name3', 2.78, 67) 
ON CONFLICT (name) DO UPDATE SET gauge=VALUES(gauge), counter=VALUES(counter)`

 Оно сработает так, но что делать в случае если 1 метрика придет 2 раза. А такое в тестах приходит, условно пакет с 2 обновлениями одной и той же метрики(я про counter которые должны прибавляться к прошлому значению по gauge все проще, можно формально вообще просто последнюю брать).
 
 + насколько я знаю, так не рекомендуется делать, наоборот каждую команду отдельно внутри транзакции. Или я что-то не понял совсем?

2024-01-26 09:45 UTC, mbiwapa commented on internal/storage/postgre/postgre.go
> +func Backoff() backoff.Algorithm {
Убрал, вынес в отдельный пакет

2024-01-29 17:28 UTC, rktkov commented on internal/storage/postgre/postgre.go
> +		stmt, err := tx.PrepareContext(ctx, `INSERT INTO metric (name, gauge, counter) VALUES ($1,$2,$3) ON CONFLICT (name) DO UPDATE SET gauge=$2, counter=$3`)
В чем проблема записи нескольких значений по одной метрике - можно ведь до формирования записывающего запроса проанализировать в коде, что записывается, и по необходимости отфильтровать то, чего не должно быть записано.

2024-01-29 17:30 UTC, rktkov approved these changes
Дискуссионые моменты можем обсудить на 1-1.

2024-02-07 06:02 UTC, merged